### ISSUE TITLE
Não consigo abrir o jogo, alguns erros são mostrados no console

### ISSUE THREAD

**Issue by cjgomes** [ArtpokeBr/Minecraft-Ultimato#208]
Baixei a instancia e coloquei no multimc, efetuou o download certinho e na hora de subir mostra o seguinte erro,

`Window size: 854 x 480

Java Arguments:
[-Xms8000m, -Xmx12000m, -Duser.language=en]

ID do processo do Minecraft: 8034

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
O processo foi encerrado com o código 255.`

Já tem bastante memória alocada, não acredito ser falta de memória, já tentei subir com as versões 1.8 do java openjdk, com a versão oficial de oracle 13.0.2 também.
Detalhe, eu uso o multimc 5 em Linux e roda o modpack do stonks craft tranquilamente.

**Comment by ArtpokeBr** [comment]
Isso é estranho, por que por mais que eu n seja perito, no crash não tem nada relacionado á algum Mod em si ou coisa do tipo, acredito ser probleminhas com o MultiMC e afins, pode ser a Curse tbm não baixando os Mods direito? complicado mas não sei a resposta pro problema não =/
