### ISSUE TITLE
Lag e crash

### ISSUE THREAD

**Issue by vaperemoji** [ArtpokeBr/Minecraft-Ultimato#308]
Versão do Modpack:
1.0.4

Descrição:
Quando entro no Modpack, meu jogo fica a 30Fps mesmo nos graficos no minimos no multi mc, ja no curseforge quando abro o jogo ele ja crasha na hora

**Sugestão de Solução:**
para o lag optfine ja para o crash nao sei

Crash Log:
[20:30:22] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:30:22] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:30:22] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:30:22] [main/INFO]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[20:30:22] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\victo\OneDrive\Documentos\curseforge\minecraft\Install\runtime\jre-x64
[20:30:22] [main/INFO]: Searching C:\Users\victo\OneDrive\Documentos\curseforge\minecraft\Instances\MC Ultimato\mods for mods
[20:30:23] [main/INFO]: Searching C:\Users\victo\OneDrive\Documentos\curseforge\minecraft\Instances\MC Ultimato\mods\1.12.2 for mods
[20:30:23] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[20:30:23] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:30:23] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[20:30:23] [main/WARN]: The coremod ObfuscatePlugin (com.mrcrayfish.obfuscate.asm.ObfuscatePlugin) is not signed!
[20:30:23] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.16.4_HD_U_G5_MOD.jar
[20:30:23] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rats-3.2.14-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:30:23] [main/WARN]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!
[20:30:23] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
[20:30:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:30:23] [main/INFO]: Loading tweak class name codechicken.asm.internal.Tweaker
[20:30:23] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[20:30:23] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[20:30:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/victo/OneDrive/Documentos/curseforge/minecraft/Instances/MC%20Ultimato/mods/VanillaFix-1.0.10-150.jar Service=LaunchWrapper Env=CLIENT
[20:30:23] [main/DEBUG]: Instantiating coremod class VanillaFixLoadingPlugin
[20:30:23] [main/INFO]: Initializing VanillaFix
[20:30:23] [main/INFO]: Initializing StacktraceDeobfuscator
[20:30:23] [main/INFO]: Found MCP method mappings: methods-stable_39.csv
[20:30:23] [main/INFO]: Done initializing StacktraceDeobfuscator
[20:30:23] [main/INFO]: Initializing Bug Fix Mixins
[20:30:23] [main/INFO]: Compatibility level set to JAVA_8
[20:30:23] [main/INFO]: Initializing Crash Fix Mixins
[20:30:23] [main/INFO]: Initializing Profiler Improvement Mixins
[20:30:23] [main/INFO]: Initializing Texture Fix Mixins
[20:30:23] [main/INFO]: Initializing Mod Support Mixins
[20:30:23] [main/DEBUG]: The coremod org.dimdev.vanillafix.VanillaFixLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[20:30:23] [main/WARN]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[20:30:23] [main/DEBUG]: Enqueued coremod VanillaFixLoadingPlugin
[20:30:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:30:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:30:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:30:23] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[20:30:23] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[20:30:23] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[20:30:23] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[20:30:23] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\victo\OneDrive\Documentos\curseforge\minecraft\Instances\MC Ultimato\mods\OptiFine_1.16.4_HD_U_G5_MOD.jar
[20:30:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:30:23] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[20:30:23] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[20:30:23] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[20:30:23] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[20:30:23] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[20:30:23] [main/DEBUG]: Injection complete
[20:30:23] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[20:30:23] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[20:30:25] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[20:30:25] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[20:30:25] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[20:30:25] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:30:25] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[20:30:25] [main/DEBUG]: Injection complete
[20:30:25] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[20:30:25] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[20:30:25] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[20:30:25] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:30:25] [main/DEBUG]: Injecting coremod MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\} class transformers
[20:30:25] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:getASMTransformerClass:99]: Successfully Registered Transformer
[20:30:25] [main/TRACE]: Registering transformer micdoodle8.mods.miccore.MicdoodleTransformer
[20:30:26] [main/DEBUG]: Injection complete
[20:30:26] [main/DEBUG]: Running coremod plugin for MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\}
[20:30:26] [main/DEBUG]: Running coremod plugin MicdoodlePlugin
[20:30:26] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[20:30:26] [main/INFO]: [micdoodle8.mods.miccore.MicdoodlePlugin:injectData:292]: [Micdoodle8Core]: Patching game...
[20:30:26] [main/DEBUG]: Coremod plugin class MicdoodlePlugin run successfully
[20:30:26] [main/INFO]: Calling tweak class codechicken.asm.internal.Tweaker
[20:30:26] [main/INFO]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[20:30:26] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[20:30:26] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@60deefed
[20:30:26] [main/DEBUG]: Injecting coremod VanillaFixLoadingPlugin \{org.dimdev.vanillafix.VanillaFixLoadingPlugin\} class transformers
[20:30:26] [main/DEBUG]: Injection complete
[20:30:26] [main/DEBUG]: Running coremod plugin for VanillaFixLoadingPlugin \{org.dimdev.vanillafix.VanillaFixLoadingPlugin\}
[20:30:26] [main/DEBUG]: Running coremod plugin VanillaFixLoadingPlugin
[20:30:26] [main/DEBUG]: Coremod plugin class VanillaFixLoadingPlugin run successfully
[20:30:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:30:26] [main/DEBUG]: Validating minecraft
[20:30:28] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:30:28] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/github/alexthe666/rats/server/misc/RatsRuntimePatcher
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.github.alexthe666.rats.server.asm.RatsPlugin.getASMTransformerClass(RatsPlugin.java:18)
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:30:28] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:30:28] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more

**Comment by ArtpokeBr** [comment]
Primeiro de Tudo, Atualize o Modpack. você está desatualizado.
