### ISSUE TITLE
Crash user do extra utilities

### ISSUE THREAD

**Issue by Christtiann** [ArtpokeBr/Minecraft-Ultimato#81]
Ao colocar um user em uma maquina do techguns crasha em server
![image](https://user-images.githubusercontent.com/54782518/101071506-78de0d80-357b-11eb-9fdd-3ee101789c5c.png)

```
Time: 2020-12-03 11:35:40 BRT
Description: Ticking block entity

java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
    at techguns.util.TextUtil.trans(TextUtil.java:8)
    at techguns.blocks.machines.BasicMachine.onBlockActivated(BasicMachine.java:208)
    at com.rwtema.extrautils2.compatibility.CompatHelper.activateBlock(CompatHelper.java:55)
    at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:245)
    at com.rwtema.extrautils2.tile.TileAdvInteractor.TickCentral_TrueITickableUpdate(TileAdvInteractor.java:94)
    at com.github.terminatornl.tickcentral.api.TickHub.trueUpdate(TickHub.java:48)
    at com.github.terminatornl.laggoggles.Main.redirectUpdate(Main.java:91)
    at com.rwtema.extrautils2.tile.TileAdvInteractor.update(TileAdvInteractor.java)
    at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
    at net.minecraft.world.World.updateEntities(World.java:2159)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:851)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:984)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:456)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:861)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 16 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: xu2:tileuse // com.rwtema.extrautils2.tile.TileUse
  Block type: ID #429 (tile.extrautils2:user // com.rwtema.extrautils2.blocks.BlockAdvInteractor$Use // extrautils2:user)
  Block data value: 2 / 0x2 / 0b0010
  Block location: World: (-2017,70,-2065), Chunk: (at 15,4,15 in -127,-130; contains blocks -2032,0,-2080 to -2017,255,-2065), Region: (-4,-5; contains chunks -128,-160 to -97,-129, blocks -2048,0,-2560 to -1537,255,-2049)
  Actual block type: ID #429 (tile.extrautils2:user // com.rwtema.extrautils2.blocks.BlockAdvInteractor$Use // extrautils2:user)
  Actual block data value: 2 / 0x2 / 0b0010
  Block Entity NBT: {extrastacks:[],select:0s,powered:0b,upgrades:{},button:0s,mode:3s,Active:1b,contents:{Size:9,Items:[{Slot:0,id:"tp:infin_bucket",Count:1b,Damage:0s}]},x:-2017,pulses:0,cooldown:20,y:70,ForgeCaps:{"nuclearcraft:capability_default_radiation_resistance":{radiationResistance:0.0d}},Frequency:1293929434,z:-2065,id:"xu2:tileuse",sneak:0b,redstone:0s}

```
Coloquei no single e nao crashou

**Comment by Christtiann** [comment]
![image](https://user-images.githubusercontent.com/54782518/101071674-afb42380-357b-11eb-8fcf-bfc9d2031495.png)
 crashou um pouco...

**Comment by ArtpokeBr** [comment]
Pro Modpack, devo colocar uma Tooltip avisando pra não misturar os dois então. mas para servidores aconselho á desativar o Mechanical user mesmo.
